name: Staging

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage-tiebreaker" #Must be unique in Heroku
          heroku_email: "aerisemusic@gmail.com"
          healthcheck: "https://stage-tiebreaker.herokuapp.com"
          delay: 5
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage-tiebreaker-api"
          heroku_email: "aerisemusic@gmail.com"
          healthcheck: "https://stage-tiebreaker-api.herokuapp.com"
          delay: 5
          rollbackonhealthcheckfailed: true
