name: Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tiebreaker" #Must be unique in Heroku
          heroku_email: "aerisemusic@gmail.com"
          healthcheck: "https://tiebreaker.herokuapp.com"
          delay: 5
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tiebreaker-api"
          heroku_email: "aerisemusic@gmail.com"
          healthcheck: "https://tiebreaker-api.herokuapp.com/health"
          delay: 5
          rollbackonhealthcheckfailed: true
